name: guyishiwang
on:
  workflow_dispatch:

  schedule:
    - cron: '40 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guyishiwang
        env:
          anfin07150: ${{ secrets.anfin07150 }}
        run: |
          printf '%s' "$anfin07150" | jq -r .eud335 | /bin/bash
          printf '%s' "$rb23224" | jq -r .ezjj2 | /bin/bash
          printf '%s' "$aokp4679" | jq -r .jl56868 | /bin/bash
          printf '%s' "$dv5" | jq -r .n2 | /bin/bash
          printf '%s' "$yk5063" | jq -r .j7905 | /bin/bash
          printf '%s' "$dd2922" | jq -r .qvwcf5 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lNo5lyo0
          path: "*.zip"
          retention-days: 1
